<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Gibo" />

<meta name="date" content="2016-05-10" />

<title>Introduzione a comuniTI</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; }
code > span.dt { color: #902000; }
code > span.dv { color: #40a070; }
code > span.bn { color: #40a070; }
code > span.fl { color: #40a070; }
code > span.ch { color: #4070a0; }
code > span.st { color: #4070a0; }
code > span.co { color: #60a0b0; font-style: italic; }
code > span.ot { color: #007020; }
code > span.al { color: #ff0000; font-weight: bold; }
code > span.fu { color: #06287e; }
code > span.er { color: #ff0000; font-weight: bold; }
</style>



<link href="data:text/css,body%20%7B%0A%20%20background%2Dcolor%3A%20%23fff%3B%0A%20%20margin%3A%201em%20auto%3B%0A%20%20max%2Dwidth%3A%20700px%3B%0A%20%20overflow%3A%20visible%3B%0A%20%20padding%2Dleft%3A%202em%3B%0A%20%20padding%2Dright%3A%202em%3B%0A%20%20font%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0A%20%20font%2Dsize%3A%2014px%3B%0A%20%20line%2Dheight%3A%201%2E35%3B%0A%7D%0A%0A%23header%20%7B%0A%20%20text%2Dalign%3A%20center%3B%0A%7D%0A%0A%23TOC%20%7B%0A%20%20clear%3A%20both%3B%0A%20%20margin%3A%200%200%2010px%2010px%3B%0A%20%20padding%3A%204px%3B%0A%20%20width%3A%20400px%3B%0A%20%20border%3A%201px%20solid%20%23CCCCCC%3B%0A%20%20border%2Dradius%3A%205px%3B%0A%0A%20%20background%2Dcolor%3A%20%23f6f6f6%3B%0A%20%20font%2Dsize%3A%2013px%3B%0A%20%20line%2Dheight%3A%201%2E3%3B%0A%7D%0A%20%20%23TOC%20%2Etoctitle%20%7B%0A%20%20%20%20font%2Dweight%3A%20bold%3B%0A%20%20%20%20font%2Dsize%3A%2015px%3B%0A%20%20%20%20margin%2Dleft%3A%205px%3B%0A%20%20%7D%0A%0A%20%20%23TOC%20ul%20%7B%0A%20%20%20%20padding%2Dleft%3A%2040px%3B%0A%20%20%20%20margin%2Dleft%3A%20%2D1%2E5em%3B%0A%20%20%20%20margin%2Dtop%3A%205px%3B%0A%20%20%20%20margin%2Dbottom%3A%205px%3B%0A%20%20%7D%0A%20%20%23TOC%20ul%20ul%20%7B%0A%20%20%20%20margin%2Dleft%3A%20%2D2em%3B%0A%20%20%7D%0A%20%20%23TOC%20li%20%7B%0A%20%20%20%20line%2Dheight%3A%2016px%3B%0A%20%20%7D%0A%0Atable%20%7B%0A%20%20margin%3A%201em%20auto%3B%0A%20%20border%2Dwidth%3A%201px%3B%0A%20%20border%2Dcolor%3A%20%23DDDDDD%3B%0A%20%20border%2Dstyle%3A%20outset%3B%0A%20%20border%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0A%20%20border%2Dwidth%3A%202px%3B%0A%20%20padding%3A%205px%3B%0A%20%20border%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0A%20%20border%2Dwidth%3A%201px%3B%0A%20%20border%2Dstyle%3A%20inset%3B%0A%20%20line%2Dheight%3A%2018px%3B%0A%20%20padding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0A%20%20border%2Dleft%2Dstyle%3A%20none%3B%0A%20%20border%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0A%20%20background%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0A%0Ap%20%7B%0A%20%20margin%3A%200%2E5em%200%3B%0A%7D%0A%0Ablockquote%20%7B%0A%20%20background%2Dcolor%3A%20%23f6f6f6%3B%0A%20%20padding%3A%200%2E25em%200%2E75em%3B%0A%7D%0A%0Ahr%20%7B%0A%20%20border%2Dstyle%3A%20solid%3B%0A%20%20border%3A%20none%3B%0A%20%20border%2Dtop%3A%201px%20solid%20%23777%3B%0A%20%20margin%3A%2028px%200%3B%0A%7D%0A%0Adl%20%7B%0A%20%20margin%2Dleft%3A%200%3B%0A%7D%0A%20%20dl%20dd%20%7B%0A%20%20%20%20margin%2Dbottom%3A%2013px%3B%0A%20%20%20%20margin%2Dleft%3A%2013px%3B%0A%20%20%7D%0A%20%20dl%20dt%20%7B%0A%20%20%20%20font%2Dweight%3A%20bold%3B%0A%20%20%7D%0A%0Aul%20%7B%0A%20%20margin%2Dtop%3A%200%3B%0A%7D%0A%20%20ul%20li%20%7B%0A%20%20%20%20list%2Dstyle%3A%20circle%20outside%3B%0A%20%20%7D%0A%20%20ul%20ul%20%7B%0A%20%20%20%20margin%2Dbottom%3A%200%3B%0A%20%20%7D%0A%0Apre%2C%20code%20%7B%0A%20%20background%2Dcolor%3A%20%23f7f7f7%3B%0A%20%20border%2Dradius%3A%203px%3B%0A%20%20color%3A%20%23333%3B%0A%20%20white%2Dspace%3A%20pre%2Dwrap%3B%20%20%20%20%2F%2A%20Wrap%20long%20lines%20%2A%2F%0A%7D%0Apre%20%7B%0A%20%20border%2Dradius%3A%203px%3B%0A%20%20margin%3A%205px%200px%2010px%200px%3B%0A%20%20padding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0A%20%20background%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0A%0Acode%20%7B%0A%20%20font%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0A%20%20font%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0A%20%20padding%3A%202px%200px%3B%0A%7D%0A%0Adiv%2Efigure%20%7B%0A%20%20text%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0A%20%20background%2Dcolor%3A%20%23FFFFFF%3B%0A%20%20padding%3A%202px%3B%0A%20%20border%3A%201px%20solid%20%23DDDDDD%3B%0A%20%20border%2Dradius%3A%203px%3B%0A%20%20border%3A%201px%20solid%20%23CCCCCC%3B%0A%20%20margin%3A%200%205px%3B%0A%7D%0A%0Ah1%20%7B%0A%20%20margin%2Dtop%3A%200%3B%0A%20%20font%2Dsize%3A%2035px%3B%0A%20%20line%2Dheight%3A%2040px%3B%0A%7D%0A%0Ah2%20%7B%0A%20%20border%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0A%20%20padding%2Dtop%3A%2010px%3B%0A%20%20padding%2Dbottom%3A%202px%3B%0A%20%20font%2Dsize%3A%20145%25%3B%0A%7D%0A%0Ah3%20%7B%0A%20%20border%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0A%20%20padding%2Dtop%3A%2010px%3B%0A%20%20font%2Dsize%3A%20120%25%3B%0A%7D%0A%0Ah4%20%7B%0A%20%20border%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0A%20%20margin%2Dleft%3A%208px%3B%0A%20%20font%2Dsize%3A%20105%25%3B%0A%7D%0A%0Ah5%2C%20h6%20%7B%0A%20%20border%2Dbottom%3A%201px%20solid%20%23ccc%3B%0A%20%20font%2Dsize%3A%20105%25%3B%0A%7D%0A%0Aa%20%7B%0A%20%20color%3A%20%230033dd%3B%0A%20%20text%2Ddecoration%3A%20none%3B%0A%7D%0A%20%20a%3Ahover%20%7B%0A%20%20%20%20color%3A%20%236666ff%3B%20%7D%0A%20%20a%3Avisited%20%7B%0A%20%20%20%20color%3A%20%23800080%3B%20%7D%0A%20%20a%3Avisited%3Ahover%20%7B%0A%20%20%20%20color%3A%20%23BB00BB%3B%20%7D%0A%20%20a%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0A%20%20%20%20text%2Ddecoration%3A%20underline%3B%20%7D%0A%20%20a%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0A%20%20%20%20text%2Ddecoration%3A%20underline%3B%20%7D%0A%0A%2F%2A%20Class%20described%20in%20https%3A%2F%2Fbenjeffrey%2Ecom%2Fposts%2Fpandoc%2Dsyntax%2Dhighlighting%2Dcss%0A%20%20%20Colours%20from%20https%3A%2F%2Fgist%2Egithub%2Ecom%2Frobsimmons%2F1172277%20%2A%2F%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%2F%2A%20Keyword%20%2A%2F%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%2F%2A%20DataType%20%2A%2F%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%2F%2A%20DecVal%20%28decimal%20values%29%20%2A%2F%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%2F%2A%20BaseN%20%2A%2F%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%2F%2A%20Float%20%2A%2F%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%2F%2A%20Char%20%2A%2F%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%2F%2A%20String%20%2A%2F%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%2F%2A%20Comment%20%2A%2F%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%2F%2A%20OtherToken%20%2A%2F%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%2F%2A%20AlertToken%20%2A%2F%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%2F%2A%20Function%20calls%20%2A%2F%20%0Acode%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%2F%2A%20ErrorTok%20%2A%2F%0A%0A" rel="stylesheet" type="text/css" />

</head>

<body>




<h1 class="title toc-ignore">Introduzione a comuniTI</h1>
<h4 class="author"><em>Gibo</em></h4>
<h4 class="date"><em>2016-05-10</em></h4>



<div id="creazione-della-lista-dei-comuni-ticinesi-a-una-determinata-data" class="section level2">
<h2>Creazione della lista dei comuni ticinesi a una determinata data</h2>
<p>Il pacchetto permette la creazione della lista dei comuni a un determinato momento, a partire dal primo gennaio del 1960. Lo si fa con la funzione <code>comuni_stato</code>, che prende come argomenti la <code>listastoricizzata</code> dei comuni e la data di riferimento che si desidera (<code>data.rif</code>, da dare in formato “aaaa-mm-gg”).</p>
<p>Per esempio, per creare la lista dei comuni al 31.12.2000:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Caricamento del pacchetto comuniTI</span>
<span class="kw">library</span>(comuniTI)

<span class="co"># Caricamento della lista storicizzata dei comuni ticinesi</span>
<span class="kw">data</span>(comuniTI)

<span class="co"># Creazione della lista dei comuni al 31.12.2000 (&quot;2000-12-31&quot;)</span>
c2000 &lt;-<span class="st"> </span><span class="kw">comuni_stato</span>(comuniTI, <span class="dt">data.rif =</span> <span class="st">&quot;2000-12-31&quot;</span>)
<span class="kw">str</span>(c2000)</code></pre>
<pre><code>## 'data.frame':    245 obs. of  15 variables:
##  $ historyMunicipalityId      : int  10381 10404 10405 10409 10411 10415 10417 10557 10558 10755 ...
##  $ districtHistId             : int  10002 10004 10042 10004 10003 10003 10004 10004 10004 10003 ...
##  $ cantonAbbreviation         : chr  &quot;TI&quot; &quot;TI&quot; &quot;TI&quot; &quot;TI&quot; ...
##  $ municipalityId             : int  5266 5135 5322 5129 5224 5225 5134 5130 5131 5233 ...
##  $ municipalityLongName       : chr  &quot;Stabio&quot; &quot;Vogorno&quot; &quot;Someo&quot; &quot;Sonogno&quot; ...
##  $ municipalityShortName      : chr  &quot;Stabio&quot; &quot;Vogorno&quot; &quot;Someo&quot; &quot;Sonogno&quot; ...
##  $ municipalityEntryMode      : int  11 11 11 11 11 11 11 11 11 11 ...
##  $ municipalityStatus         : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ municipalityAdmissionNumber: int  1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 ...
##  $ municipalityAdmissionMode  : int  20 20 20 20 20 20 20 20 20 20 ...
##  $ municipalityAdmissionDate  : Date, format: &quot;1960-01-01&quot; &quot;1960-01-01&quot; ...
##  $ municipalityAbolitionNumber: int  NA NA 2295 NA 3407 NA 3173 3406 NA NA ...
##  $ municipalityAbolitionMode  : int  NA NA 29 NA 29 NA 29 29 NA NA ...
##  $ municipalityAbolitionDate  : Date, format: NA NA ...
##  $ municipalityDateOfChange   : Date, format: &quot;1960-01-01&quot; &quot;1960-01-01&quot; ...</code></pre>
<p>Al 31.12.2000 in Ticino c’erano 245 comuni. L’oggetto creato, <code>c2000</code>, è un data frame con 245 righe e 15 colonne. Ogni riga è un comune e per ognuno di questi sono disponibili 15 colonne. Solo alcune di queste sono utili/interessanti:</p>
<ul>
<li><code>municipalityId</code>: codice federale del comune, creato dall’Ust;</li>
<li><code>municipalityLongName</code> e <code>municipalityShortName</code>: nome del comune (versione lunga e corta);</li>
<li><code>districtHistId</code>: numero storicizzato del distretto a cui appartiene il comune (serve al collegamento dei comuni con i dati dei distretti - <code>distrettiTI</code>).</li>
</ul>
</div>
<div id="collegamento-dei-dati-dei-comuni-con-i-distretti" class="section level2">
<h2>Collegamento dei dati dei comuni con i distretti</h2>
<p>Oltre alla lista storicizzata dei comuni (<code>comuniTI</code>), nel pacchetto ci sono anche dei dati con i distretti ticinesi (<code>distrettiTI</code>), che si possono caricare così:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(distrettiTI)
distrettiTI</code></pre>
<pre><code>##   districtHistId districtId         districtLongName districtShortName
## 1          10002       2106   Distretto di Mendrisio         Mendrisio
## 2          10003       2105      Distretto di Lugano            Lugano
## 3          10004       2104     Distretto di Locarno           Locarno
## 4          10005       2103   Distretto di Leventina         Leventina
## 5          10006       2102      Distretto di Blenio            Blenio
## 6          10007       2101  Distretto di Bellinzona        Bellinzona
## 7          10040       2107     Distretto di Riviera           Riviera
## 8          10042       2108 Distretto di Vallemaggia       Vallemaggia</code></pre>
<p>Ci sono gli otto distretti ticinesi che possono essere collegati con la lista dei comuni a una determinata data tramite la colonna del numero storicizzato dei distretti (<code>districtHistId</code>). Riprendendo i comuni al 31.12.2000 creati nella sezione precedente:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(c2000)</code></pre>
<pre><code>## [1] 245  15</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">c2000 &lt;-<span class="st"> </span><span class="kw">merge</span>(c2000, distrettiTI, <span class="dt">by =</span> <span class="st">&quot;districtHistId&quot;</span>)
<span class="kw">dim</span>(c2000)</code></pre>
<pre><code>## [1] 245  18</code></pre>
<p>Il nuovo data frame <code>c2000</code> ha lo stesso numero di righe (i comuni) ma tre colonne in più.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(c2000)</code></pre>
<pre><code>## 'data.frame':    245 obs. of  18 variables:
##  $ districtHistId             : int  10002 10002 10002 10002 10002 10002 10002 10002 10002 10002 ...
##  $ historyMunicipalityId      : int  10381 13251 10885 11594 11707 12329 11477 11405 12829 12346 ...
##  $ cantonAbbreviation         : chr  &quot;TI&quot; &quot;TI&quot; &quot;TI&quot; &quot;TI&quot; ...
##  $ municipalityId             : int  5266 5250 5267 5251 5242 5257 5244 5247 5253 5256 ...
##  $ municipalityLongName       : chr  &quot;Stabio&quot; &quot;Chiasso&quot; &quot;Tremona&quot; &quot;Coldrerio&quot; ...
##  $ municipalityShortName      : chr  &quot;Stabio&quot; &quot;Chiasso&quot; &quot;Tremona&quot; &quot;Coldrerio&quot; ...
##  $ municipalityEntryMode      : int  11 11 11 11 11 11 11 11 11 11 ...
##  $ municipalityStatus         : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ municipalityAdmissionNumber: int  1000 1066 1000 1000 1000 1000 1000 1000 1000 1000 ...
##  $ municipalityAdmissionMode  : int  20 26 20 20 20 20 20 20 20 20 ...
##  $ municipalityAdmissionDate  : Date, format: &quot;1960-01-01&quot; &quot;1976-04-04&quot; ...
##  $ municipalityAbolitionNumber: int  NA NA 2770 NA NA NA 2772 2770 3409 2299 ...
##  $ municipalityAbolitionMode  : int  NA NA 29 NA NA NA 29 29 29 29 ...
##  $ municipalityAbolitionDate  : Date, format: NA NA ...
##  $ municipalityDateOfChange   : Date, format: &quot;1960-01-01&quot; &quot;1976-04-04&quot; ...
##  $ districtId                 : int  2106 2106 2106 2106 2106 2106 2106 2106 2106 2106 ...
##  $ districtLongName           : chr  &quot;Distretto di Mendrisio&quot; &quot;Distretto di Mendrisio&quot; &quot;Distretto di Mendrisio&quot; &quot;Distretto di Mendrisio&quot; ...
##  $ districtShortName          : chr  &quot;Mendrisio&quot; &quot;Mendrisio&quot; &quot;Mendrisio&quot; &quot;Mendrisio&quot; ...</code></pre>
<p>Le tre colonne in più sono:</p>
<ul>
<li><code>districtId</code>: codice federale del distretto (da 2101 a 2108);</li>
<li><code>districtLongName</code> e <code>districtShortName</code>: nome del distretto a cui appartiene il comune (nelle versioni lunga e corta).</li>
</ul>
<p>Il collegamento dei distretti ai dati dei comuni permette di fare delle analisi aggregate a livello di distretti partendo da dei dati dei comuni. Banalmente, con i dati a disposizione, si possono per esempio contare i comuni per distretto (al 31.12.2000):</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">with</span>(c2000, <span class="kw">table</span>(districtShortName))</code></pre>
<pre><code>## districtShortName
##  Bellinzona      Blenio   Leventina     Locarno      Lugano   Mendrisio 
##          19          17          21          42          91          27 
##     Riviera Vallemaggia 
##           6          22</code></pre>
</div>
<div id="armonizzazione-della-lista-di-comuni-tra-una-data-e-unaltra" class="section level2">
<h2>Armonizzazione della lista di comuni tra una data e un’altra</h2>
<p>Mettiamo il caso di avere a disposizione dei dati a livello comunale al 31.12.2004 e degli altri al 31.12.2015, e che si vuole fare un’analisi della dinamica avvenuta nei comuni. Innanzitutto vediamo quanti comuni c’erano alle due date:</p>
<pre class="sourceCode r"><code class="sourceCode r">c2004 &lt;-<span class="st"> </span><span class="kw">comuni_stato</span>(comuniTI, <span class="dt">data.rif =</span> <span class="st">&quot;2004-12-31&quot;</span>)
c2015 &lt;-<span class="st"> </span><span class="kw">comuni_stato</span>(comuniTI, <span class="dt">data.rif =</span> <span class="st">&quot;2015-12-31&quot;</span>)
<span class="kw">nrow</span>(c2004)</code></pre>
<pre><code>## [1] 204</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nrow</span>(c2015)</code></pre>
<pre><code>## [1] 135</code></pre>
<p>Al 31.12.2004 i comuni ticinesi erano 204, mentre al 31.12.2015 135. Come poter paragonare i dati dei comuni alle due date?</p>
<p>Una possibilità è quella di aggregare i comuni al 31.12.2004, che erano 204, facendo in modo che ne risultino 135, come al 31.12.2015. Questo è possibile con la funzione <code>armonizza</code>, che, partendo dalla lista storicizzata e da due date di riferimento, restituisce la lista dei comuni alla data meno recente aggiungendo una colonna <code>bfs_new</code>, che indica il codice federale che quel comune avrà alla data più recente.</p>
<p>Riprendiamo l’esempio del 31.12.2004 e del 31.12.2015:</p>
<pre class="sourceCode r"><code class="sourceCode r">c2004_2015 &lt;-<span class="st"> </span><span class="kw">armonizza</span>(comuniTI, <span class="dt">data1 =</span> <span class="st">&quot;2004-12-31&quot;</span>, <span class="dt">data2 =</span> <span class="st">&quot;2015-12-31&quot;</span>)
<span class="kw">str</span>(c2004_2015)</code></pre>
<pre><code>## 'data.frame':    204 obs. of  16 variables:
##  $ historyMunicipalityId      : int  11768 11882 11494 11435 12062 12052 12054 11963 12665 12725 ...
##  $ districtHistId             : int  10007 10007 10007 10007 10007 10007 10007 10007 10007 10007 ...
##  $ cantonAbbreviation         : chr  &quot;TI&quot; &quot;TI&quot; &quot;TI&quot; &quot;TI&quot; ...
##  $ municipalityId             : int  5001 5002 5003 5004 5005 5006 5007 5008 5009 5010 ...
##  $ municipalityLongName       : chr  &quot;Arbedo-Castione&quot; &quot;Bellinzona&quot; &quot;Cadenazzo&quot; &quot;Camorino&quot; ...
##  $ municipalityShortName      : chr  &quot;Arbedo-Castione&quot; &quot;Bellinzona&quot; &quot;Cadenazzo&quot; &quot;Camorino&quot; ...
##  $ municipalityEntryMode      : int  11 11 11 11 11 11 11 11 11 11 ...
##  $ municipalityStatus         : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ municipalityAdmissionNumber: int  1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 ...
##  $ municipalityAdmissionMode  : int  20 20 20 20 20 20 20 20 20 20 ...
##  $ municipalityAdmissionDate  : Date, format: &quot;1960-01-01&quot; &quot;1960-01-01&quot; ...
##  $ municipalityAbolitionNumber: int  NA NA 2317 NA NA NA NA NA NA NA ...
##  $ municipalityAbolitionMode  : int  NA NA 26 NA NA NA NA NA NA NA ...
##  $ municipalityAbolitionDate  : Date, format: NA NA ...
##  $ municipalityDateOfChange   : Date, format: &quot;1960-01-01&quot; &quot;1960-01-01&quot; ...
##  $ bfs_new                    : int  5001 5002 5003 5004 5005 5006 5007 5008 5009 5010 ...</code></pre>
<p>L’oggetto appena creato, <code>c2004_2015</code>, ha i 204 comuni al 31.12.2004, con l’aggiunta della colonna <code>bfs_new</code>, che indica il codice federale che un comune avrà al 31.12.2015. I comuni che hanno subìto delle modifiche nel periodo tra le due date, tipo delle fusioni, avranno, nella colonna <code>bfs_new</code>, il codice federale del comune a cui apparterranno alla data più recente. Per fare un esempio, estraiamo i dati di Lugano:</p>
<pre class="sourceCode r"><code class="sourceCode r">c2004_2015[c2004_2015$bfs_new ==<span class="st"> </span><span class="dv">5192</span>, <span class="kw">c</span>(<span class="st">&quot;municipalityId&quot;</span>, <span class="st">&quot;municipalityLongName&quot;</span>, <span class="st">&quot;bfs_new&quot;</span>)]</code></pre>
<pre><code>##     municipalityId municipalityLongName bfs_new
## 95            5147             Barbengo    5192
## 102           5155                Bogno    5192
## 107           5163                Cadro    5192
## 110           5168             Carabbia    5192
## 112           5170               Carona    5192
## 114           5173              Certara    5192
## 115           5174             Cimadera    5192
## 127           5192               Lugano    5192
## 153           5224              Sonvico    5192
## 157           5229             Valcolla    5192
## 162           5235       Villa Luganese    5192</code></pre>
<p>Al 31.12.2004 esistevano i comuni di Barbengo, Bogno, Cadro, Carabbia, Carona, Certara, Cimadera, Lugano, Sonvico, Valcolla e Villa Luganese (ognuno col suo codice federale <code>municipalityId</code>). Al 31.12.2015 tutti questi comuni non esistevano più e facevano parte di Lugano. Questo lo si può vedere dalla colonna <code>bfs_new</code>, che è uguale a 5192 per tutti.</p>
<p>Da notare che la funzione <code>armonizza</code> è una nuova versione della funzione <code>aggiungi_codici_post_mutazioni</code>, che funziona allo stesso modo ma è meno “corretta”, nel senso che funzionava solo in alcuni casi. La funzione <code>armonizza</code> ha corretto alcuni errori di <code>aggiungi_codici_post_mutazioni</code>, ma comunque per il momento funziona solo a partire dal 31.12.2004 (prima, purtroppo, no).</p>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
